# Generated by Django 4.1 on 2023-04-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_player', '0002_song_user'),
        ('app_player', '0005_alter_part_dedescription_p_alter_song_description'),
    ]

    operations = [
    ]
